"""Alembic environment.

Pulls the database URL from app settings (never from alembic.ini) and binds the
declarative metadata so autogenerated diffs work after the initial migration.
"""

from __future__ import annotations

from logging.config import fileConfig
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from sqlalchemy import Connection, create_engine

from alembic import context

import app.models  # noqa: F401  -- import for side effect: registers tables on Base.metadata
from app.config import get_settings
from app.db import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _database_url() -> str:
    db_url = get_settings().database_url
    # Convert async driver URL to sync for migrations
    if db_url.startswith("postgresql+asyncpg://"):
        db_url = db_url.replace("postgresql+asyncpg://", "postgresql://")
        parsed = urlsplit(db_url)
        query_map = dict(parse_qsl(parsed.query, keep_blank_values=True))
        ssl = query_map.pop("ssl", None)
        if ssl is not None and "sslmode" not in query_map:
            # psycopg2 expects sslmode, while runtime asyncpg uses ssl.
            if ssl.lower() in {"0", "false", "disable"}:
                query_map["sslmode"] = "disable"
            else:
                query_map["sslmode"] = "require"
        query = urlencode(query_map)
        db_url = urlunsplit(
            (parsed.scheme, parsed.netloc, parsed.path, query, parsed.fragment)
        )
    return db_url


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_database_url(), future=True)
    with connectable.connect() as connection:
        do_run_migrations(connection)
    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
